### ISSUE TITLE
No transition between trot and fake limp for Maias

### ISSUE THREAD

**Issue by oOCircleofLifeOo** [deathlyrage/theisle-bugs#250]
Patch: 4636
Server: NY8 V3 (Dev Branch)
Maia has no transition between it´s trot and the fake limp, it just instantly goes into the other stance. 
From fake limping to trot again seems fine.

https://www.dropbox.com/s/0rj9m6ye2veo7l8/2017-10-26%2023-27-04.mp4?dl=0

**Comment by Souretsu** [comment]
This is actually not exclusive to Maia, but happens with all dinosaurs.  It is difficult to catch because the first time you toggle fake limping, it always transitions smoothly, as does it when spamming the fake limp key.  However if given a few seconds between key presses the transition no longer plays. Below link is a video of the above being replicated, as described, with Utah on NY2 on current public branch version, 4626.

https://www.dropbox.com/s/5w9rwnfz66rp17a/limp%20glitch_utah.mp4?dl=0

**Comment by MarianaBoni** [comment]
Duplicated. https://github.com/deathlyrage/theisle-bugs/issues/138
