### ISSUE TITLE
(New Eating/Drinking System) Getting stuck after drinking/eating.

### ISSUE THREAD

**Issue by oOCircleofLifeOo** [deathlyrage/theisle-bugs#301]
Patch: .4688 - .4691
Server: NY8 (Dev Branch, Region 2)
Example Video 1:https://www.youtube.com/watch?v=BuAz7qHrlXo
Summary: Most Species can get randomly stuck after drinking/eating (Timestamp Video 1: 0:13). Tested for herbivore- and carnivore-drinking-loops and carnivore-eating-loops.

- We have yet to find the trigger for this bug. I´ve got most of the species stuck but with varying effort and time put in. For Carno it happens consistantly (Example Video 2: https://www.youtube.com/watch?v=Nykmn3UAhmY), while for others the results vary. 

- For most species the performance of any animation (besides resting) while pressing forward ("W") will get you unstuck. For Carno it takes a little more effort and wiggeling to get unstuck (as seen in the Video 2).

- Only happend on an official server (NY8, Region 2); does not seem to happen in a privately hosted game on the Testmap.

Thanks to Punch, Yautja, Arora and Kitty-Wilson for helping/discovering those issues.

We will continue to figure out what is triggering it. I Hope this will be of help anyways.

**Edit Patch: .4765 (Date: 16.11.17):**
We finally figured out a trigger for this bug. And it seems to be pretty simple. 

**You will get stuck a 100% of the time you try to eat/drink after having performed an attack. If you spawn in and never perform an attack, you won´t get stuck while eating and drinking at all.** 

Exeptions are Galli, Trike, Shant, Camara and Pue. Those never got stuck after drinking, tho all attacks were performed before trying to drink.

Video: https://youtu.be/fTeUudEKr8g
Yautja and I eating and drinking: 1st without having attacked before (working as intended),  2nd after biting the air once before eating/drinking (getting stuck).

**Comment by YautjaFett** [comment]
It seems pretty random.  The **Sauropods** and the **Galli** don't get stuck and the **Carno** gets stuck almost every time.  It takes a little more to get the **Carno** out of it without logging.

**Comment by deathlyrage** [comment]
Possible Fix in 4728

**Comment by oOCircleofLifeOo** [comment]
Not fixed in .4737. Tested on NY8 as an Ava.

**Comment by MarianaBoni** [comment]
Was fixed on 4734, without any twitching,

**Comment by YautjaFett** [comment]
As of patch 4764, we are still occasionally getting stuck.  Circle and I started testing all dinos last night and so far, the Acro is the most noticeable.  The focus will be to get through the list to have a comprehensible report today.
*We did notice that every time Acro got stuck, you could hear his growl from a much further distance when he initiated eating.

**Comment by MarianaBoni** [comment]
More information (Patch 4770)
Getting stuck in place/sliding/twitching seems to be associated with animation transitions.
It can also be seen when changing from walk/trot/sprint.
This happens when changing said animations and turning/moving right away without letting the animation change completely.
Example video of anky changing from walk/trot/sprint and turning simultaneously:
https://youtu.be/Kbp6yXD-ad4

Example video of the same anky doing the same but leaving a second between changing from walk/trot/sprint and turning, not being affected by the getting stuck in place/sliding/twitching effect :
https://youtu.be/4_ahnrvihYU

Getting stuck and turning/sliding/twitching after eating/drinking can be associated with some kind of animation timer after it is finished.
You get unstuck if you do other actions after (roaring, attacking).
Example video of stuck anky after drinking followed by roaring/attacking and getting unstuck:
https://youtu.be/LCJvBBmWaVc

**Comment by deathlyrage** [comment]
Fixed in 4773
