### ISSUE TITLE
Nest Icon greyed out after being invited to nest.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#333]
Patch: 4798
Server: NY8 Official
After being invited to nest and accepting the invite, player went to the respawn menu and the nest button was greyed out and wasn't interact-able.
Not sure if it's a problem with the nesting mechanic or the new UI.
 ![20171122002236_1](https://user-images.githubusercontent.com/30121219/33102104-2a8cb1bc-cf13-11e7-9960-9afbcbfa5557.jpg)

**Comment by dinosauriac** [comment]
Does it do anything on the old character select screen? 

@deathlyrage nesting is getting redone in some way isn't it? From my discussions with the other UI guys they said there shouldn't even be a button here anymore. I left it in since I didn't want to go removing any functionality and wasn't sure if this was currently in use.

**Comment by MarianaBoni** [comment]
It used to work on the old UI yes

**Comment by dinosauriac** [comment]
@MarianaBoni I've set the nest button to "enabled" (since it wasn't previously). Let me know if that's fixed anything or not. If it still doesn't work, maybe deathly was halfway through reworking it when the UI overhaul happened and it's just been put on hold...?

**Comment by MarianaBoni** [comment]
@dinosauriac Still not interact-able.

**Comment by deathlyrage** [comment]
Fixed in 4858
