### ISSUE TITLE
Player List button issues

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#337]
Patch: 4825
Server: NY8 Official
The Group Invite (+), Kick/Block and Mute buttons on the Player List all blink when the mouse hovers them.
The only button who shows it has been interacted with is the Mute (last one), the other ones don't have any sound/light indicating they have been pressed.
https://youtu.be/lTGjN_WLfso

**Comment by dinosauriac** [comment]
Think I've sorted this out now, all the player options have sounds associated. Had to manually add pressed states for the highlight on click to work, since these are setup as static image changes instead of self-contained dynamic buttons.

**Comment by MarianaBoni** [comment]
Patch: 4827
The buttons now have interactive sounds and turn green when pressed. They still blink when hovered, not sure if that's intentional.
https://youtu.be/zQtZtI58Ytc

**Comment by dinosauriac** [comment]
The button image is being updated every few frames as part of a check the blueprint does, which causes the "blinkiness" when you're hovering. Not sure if there's really a way around that. I think since the main issue was lack of interaction feedback we can call this one good. Considering it's meant to look like it's on an old monitor screen it doesn't really look too out of place.
