### ISSUE TITLE
Launch loading screen freezes.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#360]
Patch: 4898
When launching the game, the first loading screen freezes for around 4seconds until it is animated again.
Steps to reproduce:
- Launch the game.
Video: https://www.youtube.com/watch?v=DTtJ4ehrcKs&feature=youtu.be

**Comment by dinosauriac** [comment]
I don't think there's really a way to fix this since it's just the game loading that's causing it. I've been adding a bit of a buffer to the start of the video so that you don't miss anything, the "bonk" of the screen activating is a couple seconds in now which hopefully syncs it closer to the moment the screen unlocks.

**Comment by MarianaBoni** [comment]
Still freezes at a later time on patch 4981

**Comment by dinosauriac** [comment]
I love that it gets stuck halfway through now so it skips the whole AE logo.

**Comment by Hypno123** [comment]
Asked a handful of players if they still had stutter issues to which they responded no. Closing this for now.
