### ISSUE TITLE
Humans can suicide by shooting at the ground/wall

### ISSUE THREAD

**Issue by Hypno123** [deathlyrage/theisle-bugs#396]
Patch: 5260
Server: Dev 8
Issue: It is possible to shoot yourself with your own gun by pressing your character's body against a surface, then firing.

To replicate:

1. Select human
2. Press your body against a surface
3. Shoot at the surface while moving towards it

Video: https://www.youtube.com/watch?v=fcL4wh5WkgA

**Comment by dinosauriac** [comment]
This is technically working as intended I believe, since bullets are meant to ricochet when hitting hard surfaces. We just don't have any feedback to show that currently. Having said that, it might be worth forcing the player's weapon to point upward when close to a wall, so that they're less likely to kill themselves.

**Comment by Hypno123** [comment]
Ricochet mechanic. Intended.
